name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  read-json:
    runs-on: ubuntu-latest
    outputs:
      json-content: ${{ steps.file.outputs.content }}
    steps:
      - uses: actions/checkout@v4

      - name: Read the file
        id: file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./apps.json

  loop-json:
    runs-on: ubuntu-latest
    needs: read-json
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Create JSON Objects
        run: |
          rm apps.json
          echo "[" > apps.json
          echo '${{ needs.read-json.outputs.json-content }}' | jq -c '.[]' | while read -r app; do
            # Extract the src field and get the last part of the URL
            src=$(echo "$app" | jq -r '.src')
            filename=$(basename "$src")
            
            # Use hashFiles() to generate the hash of the temporary file
            hash=$(cat ./apps/$filename | sha256sum | cut -d " " -f 1)
            
            # Create a new JSON object with the hash
            modified_app=$(echo "$app" | jq --arg hash "$hash" '. + {hash: $hash}')
            echo "$modified_app," >> apps.json
          done
          # Remove the last comma and close the array
          sed -i '$ s/,$//' apps.json
          echo "]" >> apps.json
          cp apps.json apps.json.tmp
          jq . apps.json.tmp > apps.json
          rm apps.json.tmp
      - uses: stefanzweifel/git-auto-commit-action@v5
