name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  read-json:
    runs-on: ubuntu-latest
    outputs:
      json-content: ${{ steps.file.outputs.content }}
    steps:
      - uses: actions/checkout@v4

      - name: Read the file
        id: file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./apps.json

  loop-json:
    runs-on: ubuntu-latest
    needs: read-json
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create JSON Objects
        run: |
          # Start the combined JSON array
          echo "[" > combined.json
          # Iterate over each app object
          echo '${{ needs.read-json.outputs.json-content }}' | jq -c '.[]' | while read -r app; do
            echo "$app," >> combined.json
          done
          # Remove the last comma and close the array
          sed -i '$ s/,$//' combined.json
          echo "]" >> combined.json

      - run: echo combined.json
